# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "jakofranko's GitHub page"
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my developer blag! This will mainly be a place to link out to my other
  GitHub projects but I might throw some thoughts up here occasionally.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jakofranko.github.io" # the base hostname & protocol for your site
github_username: jakofranko

# Build settings
markdown: kramdown

defaults:
    -
        scope:
            path: ""
            type: "pages"
        values:
            parent: "index.html"
